name: release

on:
  push:
    tags:
    - '*'
    branches-ignore:
    - '*'
    - '**/*'

jobs:

  call-build:
    uses: adevinta/maiao/.github/workflows/go.yml@main

  publish:
    runs-on: ubuntu-latest
    needs: call-build
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: maiao
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          git-review*
  autobump:
    needs: publish
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: true
          cask: false
          test-bot: false

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master
        with:
          username: ${{ (github.event_name == 'workflow_dispatch' && github.actor) || 'BrewTestBot' }}

      - name: Tap homebrew
        run: |
          brew tap "${{ github.repository }}" "https://github.com/${{ github.repository }}.git"

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.MAIAO_RELEASE_APP_ID }}
          private-key: ${{ secrets.PAIAO_RELEASE_SIGNING_KEY }}

      - name: Bump formulae
        run: |
          brew bump --open-pr ${{ github.repository }}/maiao  -v --debug
        env:
          HOMEBREW_NO_INSTALL_FROM_API: "1"
          HOMEBREW_DEVELOPER: "1"
          HOMEBREW_GITHUB_API_TOKEN: "${{ steps.app-token.outputs.token }} }}"
        # uses: Homebrew/actions/bump-formulae@master
        # continue-on-error: true
        # with:
        #   token: ${{ steps.app-token.outputs.token }}
        #   formulae: "${{ github.repository }}/maiao"