name: release

on:
  push:
    tags:
    - '*'
    branches-ignore:
    - '*'
    - '**/*'

jobs:

  call-build:
    uses: ${{ github.repository }}/.github/workflows/go.yml@${{ github.sha }}

  publish:
    runs-on: ubuntu-latest
    needs: call-build
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: maiao
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          git-review*
  bump-formulae:
    name: "Bump homebrew formulae version"
    needs: publish
    runs-on: ubuntu-latest
    steps:
    - name: "Get release app token"
      uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.MAIAO_RELEASE_APP_ID }}
        private-key: ${{ secrets.PAIAO_RELEASE_SIGNING_KEY }}
    - name: "Checkout the repository"
      uses: actions/checkout@v2
      with:
        token: ${{ steps.app-token.outputs.token }}
    - name: "Configure Git user"
      run: |
        git config --global user.name "Maiao Release Bot"
        git config --global user.email "noreply@adevinta.users.github.com"
        git config --global core.commentChar ";"
    - name: "Bump in-tree release"
      run: |
        sed -i 's,^\([ ]*tag[ ]*:[ ]*"\).*\(".*\)$,\1${{ github.ref_name }}\2,g' HomebrewFormula/maiao.rb
        sed -i 's,^\([ ]*revision[ ]*:[ ]*"\).*\(".*\)$,\1${{ github.sha }}\2,g' HomebrewFormula/maiao.rb
        git add HomebrewFormula/maiao.rb
    - name: "Open pull request"
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ steps.app-token.outputs.token }}
        commit-message: "Bump homebrew formulae version to ${{ github.ref_name }}"
        title: "Bump homebrew formulae version to ${{ github.ref_name }}"
        body: |
          This pull request was automatically created by the Maiao release workflow
          when the ${{ github.ref_name }} tag was pushed.
        branch: "bump/homebrew/${{ github.ref_name }}"
